"""constants"""

CONF_SYMBOLS = "symbols"
CONF_DECIMALS = "decimals"
CONF_UPDATE_INVERVAL = "update_interval"
CONF_API_KEY = "api_key"
CONF_API_SECRET = "api_secret"
CONF_WALLET_TOTAL = "wallet_total"
CONF_FUNDING_ASSETS = "funding_assets"
CONF_EARN_FLEXIBLE_ASSETS = "earn_flexible_assets"
CONF_EARN_LOCKED_ASSETS = "earn_locked_assets"
